WIDTH = 1200
HEIGHT = 800
NODE_SIZE = 20
OFF_SET = NODE_SIZE * 2
ROWS = (HEIGHT - OFF_SET) // NODE_SIZE 
COLUMNS = (WIDTH - OFF_SET) // NODE_SIZE
BORDER = (0x00, 0xa8, 0xe8)
BACKGROUND = (0xff, 0xff, 0xff)
